### PR TITLE
Modification fo dockerizing comet

### LINKED ISSUE #10: Dockerize COMET
The modification is to dockerize COMET.

### PR DESCRIPTION
**Pull request by efu39**
Modification fo dockerizing comet (closes #10)
1. in pom.xml
- add plugins for docker packaging
- resolve multiple SLF4J bindings

2. in CometOps.java
- check environment variables before reading from application.properties
- use getResourceAsStream() instead of configFile filepath, so properties can be loaded successfully in container

Docker image is available here: https://cloud.docker.com/repository/docker/ericafu1122/comet-spring/

### CODE REVIEW

**Comment by kthare10** [comment]
approved - no comments

**Review by kthare10 — APPROVED** [review]

**Review by congwang09 — APPROVED** [review]

**Review by mjstealey — APPROVED** [review]
provisional +1

assuming that this has been tested and runs as expected?
pom and env settings for docker w/o knowing what the docker image does with them
defer to @kthare10 and @congwang09 as to formatting of files

**Comment by mjstealey** [comment]
@ericafu1122, @kthare10, @congwang09 - I'd advocate putting the docker image code this is referencing someplace public, and not owned by any particular developer. The associated image can then be owned by the NRIG group hub account.

There are two steps to this:
1. migrate the docker code to an organization repository for project docker images (probably need to create this for COMET if you don't want it as a subdir in the main repo)
2. point the NRIG-RENCI docker hub account (https://hub.docker.com/u/rencinrig) at the repository to build the image(s) based on commit hooks

**Comment by kthare10** [comment]
@ericafu1122 - Please use 4 spaces instead of tabs for formatting the code in CometOps.java
Also, consider enclosing the code in the if block with {}

**Comment by efu39** [comment]
Thanks for the feedback. I'll create a sub-folder to store Dockerfile within this repository.  So I will create a pull request later with all modification done together.

**Pull request closed without merging**
